version: '3'

services:
  mongo_db :
    container_name : mongo_container
    image : mongo:latest
    restart : always
    volumes : 
      - mongo_db:/data/db

  nodejs_app : 
    build : 
      context : .
      target : production
    ports : 
      - 4000:3000
    environment : 
      MONGO_URI: mongodb://mongo_db:27017/birthday_reminder
    depends_on: 
      - mongo_db

volumes:
  mongo_db: {}